FROM node:20-bullseye

WORKDIR /workspace

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"

RUN corepack enable && corepack prepare pnpm@9.0.0 --activate

# docker-compose.local.yml에서 실행 커맨드를 덮어쓴다.
CMD ["bash"]
